#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

shopt -s nullglob

shell_files=(
  dot_local/bin/*
  dot_config/hypr/notify/*.sh
)

if ((${#shell_files[@]} > 0)); then
  shellcheck --check-sourced "${shell_files[@]}"
fi

gitleaks git \
  --redact \
  .