[main]
fields=name,generic
font=JetBrains Mono:size=12
#width=28
#lines=12
#horizontal-pad=16
#vertical-pad=16
#inner-pad=0
#icons-enabled=yes

#[border]
#width=2
#radius=12
#selection-radius=8

[colors]
background=1e1e2edd
text=cdd6f4ff
prompt=bac2deff
placeholder=7f849cff
input=cdd6f4ff
match=f38ba8ff
selection=585b70ff
selection-text=cdd6f4ff
selection-match=f38ba8ff
counter=7f849cff
border=f38ba8ff
