name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: curl -L https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz -o shellcheck.tar.xz && tar -xzvf shellcheck.tar.xz && mv ./shellcheck-stable ./shellcheck  && chmod +x ./shellcheck
      - name: Lint shell scripts
        run: ./shellcheck dot_local/bin/* dot_config/hypr/notify/*.sh --check-sourced

  gitleaks:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITEA_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
