# ==============================================================================
# Hyprland 0.55.2 config
# Split config entrypoint.
# Put this file at: ~/.config/hypr/hyprland.conf
# ==============================================================================

source = ~/.config/hypr/conf.d/*.conf
