max-gamma = 100

profile {
    time = 05:00
    identity = true
}

profile {
    time = 21:00
    temperature = 5200
    gamma = 0.85
}

profile {
    time = 00:30
    temperature = 4500
    gamma = 0.75
}
