# ==============================================================================
# Monitors
# ==============================================================================

monitor = DP-3, 2560x1440@179.99899, 0x0, 1

misc {
    vrr = 2
}

render {
    cm_enabled = true
    cm_auto_hdr = 1
    cm_sdr_eotf = srgb
}