# ==============================================================================
# Monitors
# ==============================================================================

monitor = , highrr, auto, 1

misc {
    vrr = 2
}

render {
    cm_enabled = true
    cm_auto_hdr = 1
    cm_sdr_eotf = srgb
}