# ==============================================================================
# Environment
# ==============================================================================

# Session identity.
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_CONFIG_DIRS,/etc/xdg
env = XDG_MENU_PREFIX,arch-

# NVIDIA stuff
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = ELECTRON_OZONE_PLATFORM_HINT,auto
