# ==============================================================================
# Environment
# ==============================================================================

# Session identity.
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# KDE app menu integration for Dolphin/KDE apps.
#env = XDG_MENU_PREFIX,plasma-

# KDE / Qt: use KDE/Breeze settings.
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt5ct:qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

env = XCURSOR_SIZE,24

# GTK: force Breeze Dark if the theme is installed.
env = GTK_THEME,Breeze-Dark
#env = GDK_DEBUG,portals
env = GTK_USE_PORTAL,0
