# Qt/KDE apps theme engine
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,hyprqt6engine
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

# KDE app menu/service cache on Arch
env = XDG_CONFIG_DIRS,/etc/xdg
env = XDG_MENU_PREFIX,arch-

# Cursor size
env = XCURSOR_SIZE,24

# Theme toggle
bind = SUPER, T, exec, theme-toggle
