# Qt/KDE apps theme engine
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,hyprqt6engine
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

# KDE app menu/service cache on Arch
env = XDG_CONFIG_DIRS,/etc/xdg
env = XDG_MENU_PREFIX,arch-

# Cursor 
# hyprctl setcursor Bibata-Modern-Classic 24
env = HYPRCURSOR_SIZE,24
# TODO: change
env = HYPRCURSOR_THEME,Bibata-Modern-Classic
# for GTK apps
# gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
# gsettings set org.gnome.desktop.interface cursor-size 24
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Classic

# Theme toggle
bind = $mainMod, T, exec, theme-toggle
bind = $mainMod SHIFT, T, exec, theme-reload

cursor {
    sync_gsettings_theme = true
    # inactive_timeout = 3
    enable_hyprcursor = true

    no_hardware_cursors = 2
    use_cpu_buffer = 2
}