# ==============================================================================
# Window rules
# ==============================================================================

# ------------------------------------------------------------------------------
# Modal dialogs
# ------------------------------------------------------------------------------
windowrule {
    name = all-modals
    match:modal = true
    force_rgbx = on
    float = on
    center = on
    dim_around = on
    suppress_event = maximize
    suppress_event = fullscreen
}

windowrule = match:class ^(dialog)$, float on, center on
windowrule = match:title ^(.*[pP]opup.*)$, stay_focused on
windowrule = match:class ^(.*)$, suppress_event maximize

windowrule {
    name = localsend-modal
    match:class = localsend
    float = on
    center = on
    size = 900 720
}

windowrule {
    name = telegram-modals
    match:class = $telegramClasses
    match:modal = true
    float = on
    center = on
    size = 900 720
    suppress_event = maximize
    suppress_event = fullscreen
}

windowrule {
    name = blueman-modal
    match:class = ^(blueman-manager)$
    float = on
    center = on
    size = (monitor_w*0.3) (monitor_h*0.4)
}

windowrule {
    name = jetbrains-welcome-modal
    match:title = $jetbrainsWelcomeTitles
    float = on
    center = on
    size = (monitor_w*0.4) (monitor_h*0.4)
}

windowrule {
    name = bitwarden-modal
    match:class = ^(Bitwarden)$
    float = on
    center = on
    size = (monitor_w*0.4) (monitor_h*0.4)
}

windowrule {
    name = auth-modals-classes
    match:class = $authDialogClasses
    float = on
    center = on
    stay_focused = on
    dim_around = on
    group = deny
    keep_aspect_ratio = on
    size = 520 260
}

# windowrule {
#     name = auth-modals-titles
#     match:title = $authDialogTitles
#     float = on
#     center = on
#     stay_focused = on
#     dim_around = on
#     group = deny
#     keep_aspect_ratio = on
#     size = 520 260
# }

windowrule {
    name = browsers-pip-modals
    match:title = $pipTitles
    float = on
    pin = on
    group = deny
    keep_aspect_ratio = on
    no_initial_focus = on
    min_size = 240 135
    max_size = 640 360
}

windowrule {
    name = xdg-portal-modals
    match:class = ^(xdg-desktop-portal-gtk)$
    float = on
    center = on
    stay_focused = on
    group = deny
    keep_aspect_ratio = on
    suppress_event = maximize, fullscreen
    size = (monitor_w*0.55) (monitor_h*0.65)
}

# windowrule {
#     name = xdg-portal-modals
#     match:class = ^(org.gtk.FileChooserNative)$
#     float = on
#     center = on
#     stay_focused = on
#     suppress_event = maximize, fullscreen
#     size = (monitor_w*0.55) (monitor_h*0.65)
# }

# windowrule {
#     name = filepicker-modals-titles
#     match:title = $fileChooserTitles
#     float = on
#     center = on
#     size = (monitor_w*0.55) (monitor_h*0.65)
#     stay_focused = on
#     suppress_event = maximize, fullscreen
# }

windowrule {
    name = android-emulator-modals
    match:class = $androidFloatingClasses
    float = on
    keep_aspect_ratio = on
    persistent_size = on
    border_size = 1
    no_shadow = on
    no_blur = on
}

windowrule {
    name = telegram
    match:class = $telegramClasses
    match:modal = false
    float = on
    center = on
    center = on
    size = 1300 740
}

windowrule {
    name = yandex-music
    match:class = ^(YandexMusic)$
    float = on
    center = on
    center = on
    size = 1300 740
}

windowrule {
    name = yazi
    match:class = yazi
    float = on
    size = 75% 75%
    center = on
}

windowrule {
    name = happ
    match:class = Happ
    float = on
    size = 1000 640
}

windowrule {
    name = kde-picker
    match:class = org.freedesktop.impl.portal.desktop.kde
    size = 1000 640
}

windowrule {
    name = rustdesk-as-modal
    match:class = ^((r|R)ustdesk)$
    float = on
    center = on
    min_size = 240 135
}