# ==============================================================================
# Keybinds: main apps + session
# ==============================================================================

bind = $mainMod, RETURN, exec, $terminal
# bind = $mainMod, D, exec, $launcher
bind = $mainMod, D, exec, ~/.config/hypr/scripts/apps-launcher.sh
bind = $mainMod SHIFT, D, exec, ~/.config/hypr/scripts/apps-launcher.sh true
bind = $mainMod, E, exec, $fileManager
# bind = $mainMod, B, exec, $browser
bind = $mainMod, Y, exec, kitty --class yazi -e yazi
bind = $mainMod, N, exec, swaync-client -t -sw


bind = $mainMod SHIFT, RETURN, exec, [float; center; size 1000 700] $terminal
bind = $mainMod SHIFT, E, exec, [float; center; size 1200 800] $fileManager

bind = $mainMod, Q, killactive
bind = $mainMod SHIFT, Q, forcekillactive
bind = $mainMod SHIFT, R, exec, ~/.config/hypr/scripts/reload-config.sh

bind = $mainMod, L, exec, ~/.config/hypr/scripts/lock-now.sh
bind = $mainMod, F11, exec, ~/.config/hypr/scripts/toggle-caffeine.sh
bind = $mainMod, Delete, exec, ~/.config/hypr/scripts/power-menu.sh

bind = $mainMod, V, exec, ~/.config/hypr/scripts/cliphist-toggle.sh
bind = $mainMod SHIFT, V, exec, cliphist wipe

bind = $mainMod, T, exec, ~/.config/hypr/scripts/toggle-theme.sh