# ==============================================================================
# Keybinds: main apps + session
# ==============================================================================

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, D, exec, $launcher
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, B, exec, $browser

bind = $mainMod SHIFT, RETURN, exec, [float; center; size 1000 700] $terminal
bind = $mainMod SHIFT, E, exec, [float; center; size 1200 800] $fileManager

bind = $mainMod, Q, killactive
bind = $mainMod, M, exec, hyprctl dispatch exit
bind = $mainMod SHIFT, R, exec, ~/.config/hypr/scripts/reload-config.sh

bind = $mainMod, L, exec, ~/.config/hypr/scripts/lock-now.sh
bind = $mainMod, F11, exec, ~/.config/hypr/scripts/toggle-caffeine.sh
bind = $mainMod, Delete, exec, ~/.config/hypr/scripts/power-menu.sh