# ==============================================================================
# Keybinds: windows / mouse / focus
# ==============================================================================

bind = $mainMod, Tab, exec, $scriptsDir/toggle-tab-smart.sh

# Mouse window movement/resizing.
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Window state.
bind = $mainMod, F, fullscreen, 1
bind = $mainMod SHIFT, F, togglefloating
bind = $mainMod SHIFT, P, pin

# TODO: check
# Hide/show scratchpad:
# SUPER + SHIFT + S on a normal window -> move it to special:hidden.
# SUPER + SHIFT + S on a window already in special:hidden -> return it back.
# SUPER + S -> show/hide special:hidden.
bind = $mainMod SHIFT, S, exec, $scriptsDir/toggle-window-scratch.sh
bind = $mainMod, S, togglespecialworkspace, scratch

# TODO: check
# # Group/tabbing controls.
bind = $mainMod, G, togglegroup
bind = $mainMod SHIFT, Tab, cyclenext
bind = $mainMod SHIFT, O, moveoutofgroup
bind = $mainMod SHIFT, G, denywindowfromgroup, toggle

# Focus movement.
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Move/swap tiled windows inside current workspace.
bind = $mainMod SHIFT, left, swapwindow, l
bind = $mainMod SHIFT, right, swapwindow, r
bind = $mainMod SHIFT, up, swapwindow, u
bind = $mainMod SHIFT, down, swapwindow, d

# Alternative tiled movement.
bind = $mainMod CTRL, left, movewindow, l
bind = $mainMod CTRL, right, movewindow, r
bind = $mainMod CTRL, up, movewindow, u
bind = $mainMod CTRL, down, movewindow, d

# Preselect split direction for the next window.
bind = $mainMod ALT, left, layoutmsg, preselect l
bind = $mainMod ALT, right, layoutmsg, preselect r
bind = $mainMod ALT, up, layoutmsg, preselect u
bind = $mainMod ALT, down, layoutmsg, preselect d

# Move active window to another monitor.
bind = $mainMod SHIFT, H, movewindow, mon:-1
bind = $mainMod SHIFT, L, movewindow, mon:+1
