# ==============================================================================
# Keybinds: screenshots / screen recording helpers
# ==============================================================================

# Print — full screen: save + copy.
bind = , Print, exec, ~/.config/hypr/scripts/screenshot.sh

# Ctrl + Print — selected area: save + copy/freezed area helper.
bind = CTRL, Print, exec, ~/.config/hypr/scripts/screenshot-area.sh

# # Super + Print — selected area -> swappy editor.
bind = $mainMod, Print, exec, grim -g "$(slurp)" - | swappy -f -
# TODO: add separate binds for full screen and part of the screen

bind = SHIFT, Print, exec, ~/.config/hypr/scripts/record-region.sh

# TODO: add copying to clipboard
# Super + Shift + Print — full screen record
bind = $mainMod SHIFT, Print, exec, ~/.config/hypr/scripts/record-screen.sh
