# ==============================================================================
# Keybinds: clipboard history
# ==============================================================================

bind = $mainMod, V, exec, ~/.config/hypr/scripts/cliphist-toggle.sh
bind = $mainMod ALT, V, exec, cliphist list | fuzzel --dmenu --prompt='Clipboard > ' --width=70 --lines=20 | cliphist decode | wl-copy
bind = $mainMod SHIFT, V, exec, cliphist wipe