# ==============================================================================
# Misc
# ==============================================================================

bind = $mainMod, F11, exec, ~/.config/hypr/scripts/toggle-caffeine.sh

misc {
    focus_on_activate = true
}

# decoration {
#     rounding = 10                  # Rounded window corners like macOS
#     blur {
#         enabled = true
#         size = 8                   # Deep, frosted glass effect
#         passes = 3
#     }
# }

# animations {
#     enabled = true                 # Smooth window transitions
#     bezier = myBezier, 0.05, 0.9, 0.1, 1.05
#     animation = windows, 1, 5, myBezier
# }

bind = $mainMod SHIFT, U, exec, dotfiles-update